#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -x
if [ -d $OPENSHIFT_REPO_DIR/diy/server.xml ]
then
	echo "starting tomcat"
    cp -rf $OPENSHIFT_REPO_DIR/diy/server.xml $OPENSHIFT_DATA_DIR/apache-tomcat-7.0.54/conf
fi
