#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -x
if [ -a ${OPENSHIFT_REPO_DIR}diy/server.xml ]
then
	echo "starting tomcat"
	cd ${OPENSHIFT_REPO_DIR}diy
	mv server.xml ${OPENSHIFT_DATA_DIR}tomcat/conf
fi
"removing work directory"
rm -rf ${OPENSHIFT_DATA_DIR}/tomcat/work
echo "work directory removed"
cd ${OPENSHIFT_DATA_DIR}/tomcat
rsync -r --delete --exclude ".*" ${OPENSHIFT_REPO_DIR}/diy/webapps/ ${OPENSHIFT_DATA_DIR}/tomcat/webapps/
echo "webapps folder copied"
echo "starting application server"
cd ${OPENSHIFT_DATA_DIR}tomcat/bin
sh startup.sh
echo "application server started"