#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -x
#if [ -a ${OPENSHIFT_REPO_DIR}diy/server.xml ]
#then
	client_result "starting tomcat"
	cp -f ${OPENSHIFT_REPO_DIR}asdbasdbuoasvuidasvuidavuidiy/server.xml ${OPENSHIFT_DATA_DIR}tomcat/conf
#fi
